networks:
  public:
    external: true

services:
  code-server:
    command: --auth none --disable-telemetry
    container_name: code-server
    image: ghcr.io/coder/code-server:${IMAGE_TAG:-latest}
    labels:
      homepage.group: NAS
      homepage.href: https://${HOST:-coder.${BASE_DOMAIN}}
      homepage.icon: code.png
      homepage.name: VS Code
      traefik.enable: true
      traefik.http.routers.coder.middlewares: 'authelia@docker'
      traefik.http.routers.coder.rule: Host(`${HOST:-coder.${BASE_DOMAIN}}`)
      traefik.http.routers.coder.tls.certresolver: myresolver
      traefik.http.routers.coder.tls.domains[0].main: ${TLS_CERT_DOMAIN:-${BASE_DOMAIN}}
      traefik.http.routers.coder.tls.domains[0].sans: ${TLS_CERT_SANS:-*.${BASE_DOMAIN}}
    networks:
      - public
    pull_policy: always
    restart: unless-stopped
    user: '568:568'
    volumes:
      - /mnt/pool0/containers/coder/.config:/home/coder/.config
      - /mnt/pool0/containers/coder/.local:/home/coder/.local
      - /mnt/pool0:/mnt/pool0
      - /mnt/pool1:/mnt/pool1
