name: wineandcats-${STAGE}
networks:
  default:
    name: wineandcats-${STAGE}
  public:
    external: true

services:
  adminer:
    container_name: wineandcats-${STAGE}-adminer
    healthcheck:
      start_period: 5s
      test: 'wget --spider -q --tries=1 http://localhost:8080'
    image: adminer:5
    labels:
      - homepage.group=Other
      - homepage.href=https://db.${HOST}?pgsql=db&username=gomp&db=gomp
      - homepage.icon=adminer.png
      - homepage.name=Wine & Cats (${STAGE}) DB
      - traefik.enable=true
      - traefik.http.routers.db-wineandcats-${STAGE}.rule=Host(`db.${HOST}`)
      - traefik.http.routers.db-wineandcats-${STAGE}.tls.certresolver=myresolver
      - traefik.http.routers.db-wineandcats-${STAGE}.tls.domains[0].main=${TLS_CERT_DOMAIN:-db.${HOST}}
      - traefik.http.routers.db-wineandcats-${STAGE}.tls.domains[0].sans=${TLS_CERT_SANS}
      - traefik.http.services.db-wineandcats-${STAGE}.loadbalancer.server.port=8080
    networks:
      - default
      - public
    pull_policy: always
    restart: unless-stopped
  app:
    container_name: wineandcats-${STAGE}
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://gomp:${DB_PASSWORD}@db/gomp?sslmode=disable
      IS_DEVELOPMENT: ${IS_DEVELOPMENT:-0}
      SECURE_KEY: ${SECURE_KEY}
    image: ghcr.io/chadweimer/gomp:${IMAGE_TAG:-latest}
    labels:
      - homepage.group=Other
      - homepage.href=https://${HOST}
      - homepage.icon=https://${HOST}/static/assets/icon/icon192.png
      - homepage.name=Wine & Cats (${STAGE})
      - traefik.enable=true
      - traefik.http.routers.wineandcats-${STAGE}.rule=Host(`${HOST}`)
      - traefik.http.routers.wineandcats-${STAGE}.tls.certresolver=myresolver
      - traefik.http.routers.wineandcats-${STAGE}.tls.domains[0].main=${TLS_CERT_DOMAIN:-${HOST}}
      - traefik.http.routers.wineandcats-${STAGE}.tls.domains[0].sans=${TLS_CERT_SANS}
    networks:
      - default
      - public
    pull_policy: always
    restart: unless-stopped
    user: '568:568'
    volumes:
      - /mnt/pool0/containers/wineandcats-${STAGE}/app:/var/app/gomp/data
  db:
    container_name: wineandcats-${STAGE}-db
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: gomp
    healthcheck:
      start_period: 5s
      test: ['CMD', 'pg_isready', '-d', 'gomp']
    image: postgres:${PG_VERSION}
    networks:
      - default
    pull_policy: always
    restart: unless-stopped
    volumes:
      - /mnt/pool0/containers/wineandcats-${STAGE}/pg${PG_VERSION}/data:/var/lib/postgresql/data
